Repository KKWJ-DGU/FoDong-SERVER, pull requests merged in 2023-10, with the labels that each got.

#31 [Feat] #29 - 식당 검색 API
  src/main/java/Fodong/serverdong/domain/restaurant/controller/RestaurantController.java
  src/main/java/Fodong/serverdong/domain/restaurant/dto/response/ResponseSearchRestaurantDto.java
  src/main/java/Fodong/serverdong/domain/restaurant/repository/RestaurantQueryRepository.java
  src/main/java/Fodong/serverdong/domain/restaurant/repository/RestaurantQueryRepositoryImpl.java
  src/main/java/Fodong/serverdong/domain/restaurant/service/RestaurantService.java
  src/main/java/Fodong/serverdong/global/exception/CustomErrorCode.java
  src/test/java/Fodong/serverdong/domain/restaurant/service/RestaurantServiceTest.java
Labels: Feat ⚡, 챈 🍒

#41 [Setting] #40 - jwt 설정 파일 추가
  .github/workflows/build-deploy.yml
  build.gradle
  scripts/deploy.sh
  src/main/java/Fodong/serverdong/domain/member/controller/MemberController.java
  src/main/java/Fodong/serverdong/domain/member/dto/request/SocialLoginRequest.java
  src/main/java/Fodong/serverdong/domain/member/enums/SocialType.java
  src/main/java/Fodong/serverdong/domain/member/repository/MemberRepository.java
  src/main/java/Fodong/serverdong/domain/member/service/MemberService.java
  src/main/java/Fodong/serverdong/domain/memberToken/MemberToken.java
  src/main/java/Fodong/serverdong/domain/memberToken/dto/response/FilterProcessingTokenDto.java
  src/main/java/Fodong/serverdong/domain/memberToken/dto/response/ResponseMemberTokenDto.java
  src/main/java/Fodong/serverdong/domain/memberToken/dto/response/ResponseTokenDto.java
  src/main/java/Fodong/serverdong/domain/memberToken/dto/response/TokenInfoDto.java
  src/main/java/Fodong/serverdong/domain/memberToken/repository/MemberTokenRepository.java
  src/main/java/Fodong/serverdong/global/auth/adapter/MemberAdapter.java
  src/main/java/Fodong/serverdong/global/auth/enums/TokenStatus.java
  src/main/java/Fodong/serverdong/global/auth/filter/ExceptionHandlerFilter.java
  src/main/java/Fodong/serverdong/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/Fodong/serverdong/global/auth/oauth/KakaoSocialLogin.java
  src/main/java/Fodong/serverdong/global/auth/service/JwtService.java
  src/main/java/Fodong/serverdong/global/config/SecurityConfig.java
  src/main/java/Fodong/serverdong/global/config/WebClientConfig.java
  src/main/java/Fodong/serverdong/global/exception/CustomErrorCode.java
  src/main/java/Fodong/serverdong/global/exception/CustomExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/Fodong/serverdong/domain/member/service/KakaoSocialLoginTest.java
  src/test/java/Fodong/serverdong/global/auth/jwtServiceTest.java
Labels: Feat ⚡, Setting ⚙️, 챈 🍒

#42 [Refactor] #11 - JWT 필터에서 스웨거 URL 제외 처리
  src/main/java/Fodong/serverdong/global/auth/filter/JwtAuthenticationFilter.java
Labels: Refactor 🚿, 우욤 🐣

#43 [Fix] #11 - JWT 필터 스웨거 URL 수정
  src/main/java/Fodong/serverdong/global/auth/filter/JwtAuthenticationFilter.java
Labels: Fix 🔧, 우욤 🐣

#44 [Fix] #11 - JWT 필터 스웨거 URL 수정
  src/main/java/Fodong/serverdong/global/auth/filter/JwtAuthenticationFilter.java
Labels: Fix 🔧, 우욤 🐣

#45 [Fix] #1 - 스웨거 Path 변경
  src/main/resources/application.yml
Labels: Fix 🔧, 챈 🍒

#47 Feat/#11 JWT 재발급 오류 수정
  src/main/java/Fodong/serverdong/domain/member/controller/MemberController.java
  src/main/java/Fodong/serverdong/domain/memberToken/repository/MemberTokenQueryRepository.java
  src/main/java/Fodong/serverdong/domain/memberToken/repository/MemberTokenQueryRepositoryImpl.java
  src/main/java/Fodong/serverdong/global/auth/service/JwtService.java
Labels: Fix 🔧, 우욤 🐣

#49 [Fix] #11 - 회원 이메일 조회 쿼리문 수정
  src/main/java/Fodong/serverdong/domain/memberToken/repository/MemberTokenQueryRepositoryImpl.java
Labels: Fix 🔧, 우욤 🐣

#48 [Feat] #36 - 회원 닉네임 설정
  src/main/java/Fodong/serverdong/domain/member/Member.java
  src/main/java/Fodong/serverdong/domain/member/controller/MemberController.java
  src/main/java/Fodong/serverdong/domain/member/dto/request/RequestMemberNicknameDto.java
  src/main/java/Fodong/serverdong/domain/member/dto/request/SocialLoginRequest.java
  src/main/java/Fodong/serverdong/domain/member/repository/MemberRepository.java
  src/main/java/Fodong/serverdong/domain/member/service/MemberService.java
  src/main/java/Fodong/serverdong/global/auth/oauth/KakaoSocialLogin.java
  src/main/java/Fodong/serverdong/global/exception/CustomErrorCode.java
  src/test/java/Fodong/serverdong/domain/member/service/MemberServiceTest.java
Labels: Feat ⚡, 우욤 🐣

#51 [Feat] #11 - JWT 재발급 API 추가
  src/main/java/Fodong/serverdong/domain/memberToken/controller/MemberTokenController.java
Labels: Feat ⚡, 우욤 🐣

#53 [Feat] #37 - 회원 정보 조회
  src/main/java/Fodong/serverdong/domain/member/controller/MemberController.java
  src/main/java/Fodong/serverdong/domain/member/dto/response/ResponseMemberInfoDto.java
  src/main/java/Fodong/serverdong/domain/member/service/MemberService.java
  src/test/java/Fodong/serverdong/domain/member/service/MemberServiceTest.java
Labels: Feat ⚡, 우욤 🐣

#55 [Setting] #4 - MemberToken , wishlist 테이블 수정
  src/main/java/Fodong/serverdong/domain/wishlist/Wishlist.java
  src/main/resources/query/h2/schema-h2.sql
Labels: Fix 🔧, Setting ⚙️, 챈 🍒

#56 [Fix] #6 - 트러블슈팅 해결
  src/main/resources/application.yml
Labels: Fix 🔧, 챈 🍒

#57 [Fix] #11 - JWT 필터 토큰 검사 로직 수정
  src/main/java/Fodong/serverdong/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/Fodong/serverdong/global/auth/service/JwtService.java
  src/test/java/Fodong/serverdong/global/auth/JwtServiceTest.java
Labels: Fix 🔧, 우욤 🐣

#58 [Feat] #54 - 위시리스트 추가
  src/main/java/Fodong/serverdong/domain/restaurantCategory/repository/RestaurantCategoryRepository.java
  src/main/java/Fodong/serverdong/domain/wishlist/controller/WishlistController.java
  src/main/java/Fodong/serverdong/domain/wishlist/dto/request/RequestWishlistCreationDto.java
  src/main/java/Fodong/serverdong/domain/wishlist/dto/request/RequestWishlistDto.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistRepository.java
  src/main/java/Fodong/serverdong/domain/wishlist/service/WishlistService.java
  src/test/java/Fodong/serverdong/domain/wishlist/service/WishlistServiceTest.java
Labels: Feat ⚡, 우욤 🐣

#60 [Feat] #59 - 위시리스트 삭제
  src/main/java/Fodong/serverdong/domain/wishlist/controller/WishlistController.java
  src/main/java/Fodong/serverdong/domain/wishlist/dto/request/RequestAddWishlistDto.java
  src/main/java/Fodong/serverdong/domain/wishlist/dto/request/RequestDeleteWishlistDto.java
  src/main/java/Fodong/serverdong/domain/wishlist/dto/request/RequestWishlistCreationDto.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistRepository.java
  src/main/java/Fodong/serverdong/domain/wishlist/service/WishlistService.java
  src/test/java/Fodong/serverdong/domain/wishlist/service/WishlistServiceTest.java
Labels: Feat ⚡, 우욤 🐣

#63 [Setting] #62 - Swagger jwt 토큰 버튼 생성
  src/main/java/Fodong/serverdong/global/config/SwaggerConfig.java
Labels: Setting ⚙️, 챈 🍒

#64 [Setting] #62 - Swagger 토큰 버튼 생성
  src/main/java/Fodong/serverdong/global/config/SwaggerConfig.java
Labels: Setting ⚙️, 챈 🍒

#65 [Feat] #61 - 위시리스트 식당 조회
  src/main/java/Fodong/serverdong/domain/wishlist/controller/WishlistController.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistQueryRepository.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistQueryRepositoryImpl.java
  src/main/java/Fodong/serverdong/domain/wishlist/service/WishlistService.java
  src/test/java/Fodong/serverdong/domain/wishlist/service/WishlistServiceTest.java
Labels: Feat ⚡, 우욤 🐣

#67 [Feat] #59 - wishCount 감소
  src/main/java/Fodong/serverdong/domain/restaurant/Restaurant.java
  src/main/java/Fodong/serverdong/domain/wishlist/service/WishlistService.java
Labels: Feat ⚡, 우욤 🐣

#66 [Feat] #54 - wishCount 증가
  src/main/java/Fodong/serverdong/domain/restaurant/Restaurant.java
  src/main/java/Fodong/serverdong/domain/wishlist/service/WishlistService.java
Labels: Feat ⚡, 우욤 🐣

#68 [Setting] #62 - Swagger 문서 토큰 별 그룹화
  src/main/java/Fodong/serverdong/domain/category/controller/CategoryController.java
  src/main/java/Fodong/serverdong/domain/member/controller/MemberController.java
  src/main/java/Fodong/serverdong/global/config/SwaggerConfig.java
Labels: Setting ⚙️, 챈 🍒

#69 [Setting] #62 - yml active 변경
  src/main/resources/application.yml
Labels: Setting ⚙️, 챈 🍒

#72 [Refactor] #61 - categoryID 기본값 설정
  src/main/java/Fodong/serverdong/domain/wishlist/controller/WishlistController.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistQueryRepositoryImpl.java
Labels: Refactor 🚿, 우욤 🐣

#70 [Fix] #11 - JWT 필터 에러처리 수정
  src/main/java/Fodong/serverdong/global/auth/filter/ExceptionHandlerFilter.java
  src/main/java/Fodong/serverdong/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/Fodong/serverdong/global/auth/service/JwtService.java
  src/main/java/Fodong/serverdong/global/exception/CustomErrorCode.java
  src/test/java/Fodong/serverdong/global/auth/JwtServiceTest.java
Labels: Fix 🔧, 우욤 🐣

#74 [Feat] #11 - 소셜 로그인 요청 방식 변경
  src/main/java/Fodong/serverdong/domain/member/controller/MemberController.java
  src/main/java/Fodong/serverdong/domain/member/dto/request/RequestSocialLoginDto.java
Labels: Feat ⚡, 우욤 🐣

#77 [Feat] #29 - 식당 검색 API 반환값에 선택된 카테고리 ID 추가
  src/main/java/Fodong/serverdong/domain/restaurant/controller/RestaurantController.java
  src/main/java/Fodong/serverdong/domain/restaurant/dto/response/ResponseSearchApiDto.java
  src/main/java/Fodong/serverdong/domain/restaurant/service/RestaurantService.java
Labels: Feat ⚡, 챈 🍒
