Repository KKWJ-DGU/FoDong-SERVER, pull requests merged in 2023-11, with the labels that each got.

#79 [Setting] #4 - wishlist 테이블 수정
  src/main/java/Fodong/serverdong/domain/restaurant/repository/RestaurantQueryRepositoryImpl.java
  src/main/java/Fodong/serverdong/domain/wishlist/Wishlist.java
  src/main/java/Fodong/serverdong/domain/wishlist/dto/request/RequestWishlistCreationDto.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistQueryRepositoryImpl.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistRepository.java
  src/main/java/Fodong/serverdong/domain/wishlist/service/WishlistService.java
  src/main/resources/query/h2/schema-h2.sql
  src/main/resources/query/server/schema-server.sql
Labels: Fix 🔧, Setting ⚙️, 우욤 🐣

#80 [Feat] #71 - 위시리스트 카테고리 리스트 조회
  src/main/java/Fodong/serverdong/domain/wishlist/controller/WishlistController.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistQueryRepository.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistQueryRepositoryImpl.java
  src/main/java/Fodong/serverdong/domain/wishlist/service/WishlistService.java
  src/test/java/Fodong/serverdong/domain/wishlist/service/WishlistServiceTest.java
Labels: Feat ⚡, 우욤 🐣

#81 [Refactor] #61 - 위시리스트 식당 조회 파라미터 수정
  src/main/java/Fodong/serverdong/domain/wishlist/controller/WishlistController.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistQueryRepository.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistQueryRepositoryImpl.java
  src/main/java/Fodong/serverdong/domain/wishlist/service/WishlistService.java
Labels: Refactor 🚿, 우욤 🐣

#82 [Refactor] #61 - 위시리스트 식당 조회 식당id 추가
  src/main/java/Fodong/serverdong/domain/wishlist/controller/WishlistController.java
  src/main/java/Fodong/serverdong/domain/wishlist/dto/response/ResponseWishlistRestaurantDto.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistQueryRepository.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistQueryRepositoryImpl.java
  src/main/java/Fodong/serverdong/domain/wishlist/service/WishlistService.java
Labels: Refactor 🚿, 우욤 🐣

#83 [Refactor] #61 - 위시리스트 식당 조회 정렬 수정
  src/main/java/Fodong/serverdong/domain/wishlist/dto/response/ResponseWishlistRestaurantDto.java
  src/main/java/Fodong/serverdong/domain/wishlist/repository/WishlistQueryRepositoryImpl.java
  src/main/java/Fodong/serverdong/domain/wishlist/service/WishlistService.java
Labels: Refactor 🚿, 우욤 🐣

#84 [Feat] #18 - 식당 정보 조회 API 반환값에 식당 주소, 메뉴 정보 추가
  src/main/java/Fodong/serverdong/domain/restaurant/controller/RestaurantController.java
  src/main/java/Fodong/serverdong/domain/restaurant/dto/response/ResponseMenuInfo.java
  src/main/java/Fodong/serverdong/domain/restaurant/dto/response/ResponseRestaurantInfoDto.java
  src/main/java/Fodong/serverdong/domain/restaurant/repository/RestaurantQueryRepository.java
  src/main/java/Fodong/serverdong/domain/restaurant/repository/RestaurantQueryRepositoryImpl.java
  src/main/java/Fodong/serverdong/domain/restaurant/service/RestaurantService.java
Labels: Feat ⚡, 챈 🍒
